### ISSUE TITLE
Error about jacl2 plugin when calling cli scripts

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#1215]
### What is the bug?

When calling `php lizmap/scripts/script.php lizmap~wmts:capabilities montpellier montpellier`, there are some errors like 

See comments jelix/jelix#314

It seems this is a bad configuration in lizmap

### Environment

- Lizmap version: 3.2

**Comment by paolomartinis** [comment]
in my windows 10 environment the problem persists... I tried 3 different installations (3.2 with xampp and an old php, 3.2.3 with apache and php 7.3.11, current master 3.4.0pre.190808 with apache and php 7.3.11).
same as for others during the installation it says all is ok:
`C:\webserver\lizmap\prod\master>php lizmap\install\installer.php
Installation start..
[notice] Installation starts for the entry point index
All modules dependencies are ok
Module jelix installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauthdb_admin installed
Module master_admin installed
Module jcommunity installed
Module admin installed
Module lizmap installed
Module view installed
Module dataviz installed
Module dynamicLayers installed
Module filter installed
Module proj4php installed
All modules are installed or upgraded for the entry point index
[notice] Installation starts for the entry point admin
All modules dependencies are ok
Module jelix installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauthdb_admin installed
Module master_admin installed
Module jcommunity installed
Module admin installed
Module lizmap installed
Module view installed
Module dataviz installed
Module dynamicLayers installed
Module filter installed
Module proj4php installed
All modules are installed or upgraded for the entry point admin
[notice] Installation starts for the entry point script
All modules dependencies are ok
Module jelix installed
Module jacl2 installed
Module jacl2db installed
Module jacl2db_admin installed
Module jauthdb_admin installed
Module master_admin installed
Module jcommunity installed
Module admin installed
Module lizmap installed
Module view installed
Module dataviz installed
Module dynamicLayers installed
Module filter installed
Module proj4php installed
All modules are installed or upgraded for the entry point script
Installation ended.`
but running the script for cache generation there's the error:
`C:\webserver\lizmap\prod\master>php lizmap/scripts/script.php lizmap~wmts:capabilities 1 OLBIA
Error during initialization: \n* Error in main configuration on pluginsPath -- Path given in pluginsPath for the module jacl2db is ignored, since this module is unknown or deactivated (C:\webserver\lizmap\prod\master\lib\jelix\core\jConfigCompiler.class.php 431)
* Error in the main configuration. A plugin doesn't exist -- The coord plugin jacl2 is unknown. (C:\webserver\lizmap\prod\master\lib\jelix\core\jConfigCompiler.class.php 172)`
`C:\webserver\lizmap\prod\master>php lizmap/scripts/script.php lizmap~wmts:capabilities -v 1 OLBIA ACQ_RAMI EPSG:3857
Error during initialization: \n* Error in main configuration on pluginsPath -- Path given in pluginsPath for the module jacl2db is ignored, since this module is unknown or deactivated (C:\webserver\lizmap\prod\master\lib\jelix\core\jConfigCompiler.class.php 431)
* Error in the main configuration. A plugin doesn't exist -- The coord plugin jacl2 is unknown. (C:\webserver\lizmap\prod\master\lib\jelix\core\jConfigCompiler.class.php 172)`

**Comment by nboisteault** [comment]
@paolomartinis Give a try to [vagrant](https://github.com/3liz/lizmap-web-client/tree/master/vagrant). It avoids issues with Windows.

**Comment by laurentj** [comment]
It's a really strange error that I never reproduced.

@paolomartinis , if your are ok, I would like a zip archive with theses files:

- all files from lizmap/var/config/ except the profiles.ini.php (I don't want your credentials :-) ). I don't need lizmapConfig.ini.php too.
- all files *~config.ini.php.conf.php from  temp/lizmap/

Don't publish your zip here, send it to me by mail instead: ljouanneau@3liz.com.

**Comment by ygorigor** [comment]
I also tried this command on Windows 10 and get the same error

**Comment by paolomartinis** [comment]
@laurentj : I sent you the mail, thanks for the interest.
@nboisteault : I tried to build a vm with vagrant, but I had some problems and it didn't work (maybe because I changed some things to have qgis 3.4ltr) so I started from the scratch with Ubuntu (where I had other problems with fastcgi: I think I solved them but I want to test it more before reporting a new issue).
anyway, is it normal that the zip download from github misses the files inside the vagrant directory (cloning from github worked)? maybe can it have some connections with the bad installation in windows for other files? (I think that the common windows user downloads the source code by zip).
thanks and have a nice evening

**Comment by nboisteault** [comment]
I did not have issues with Vagrant in Windows 7 nor with Ubuntu 18.04 using QGIS 3.4. Please tell us what is not working. Vagrant directory is not part of zip because it has been created for development so you have it only using `git clone`.

**Comment by paolomartinis** [comment]
I'll post here the problems I had yerterday with Vagrant, let me know if is better to report it in a new issue.
I followed the tutorial https://github.com/3liz/lizmap-web-client/tree/master/vagrant

1. changed `vagrant/vars/custom.yml` from `vagrant/vars/custom.yml.latest` to the following:

```
---
# Define custom variables to overrides defaults for roles

# Local configuration
local_timezone: Europe/Rome
local_locale: it_IT.UTF-8
local_locale_left: it_IT
local_locale_right: UTF-8

# PHP
php_apt_key_url: https://packages.sury.org/php/apt.gpg
php_version: "7.2"
php_repository: https://packages.sury.org/php
php_composer_version: 1.7.2

# lizmap_hostname: lizmap.local
# lizmap_webserver_group: www-data

# Enable the storage of users, acl and other lizmap data into the PostgreSQL database
# lizmap_postgresql_storage: false

# Enable to check the authentication against an ldap directory
#lizmap_ldapdao_enabled: false

# Qgis server
qgis_server_version: 3.4
qgis_server_name: qgis
qgis_server_port: 8200
qgis_set_real_ip: 127.0.0.1
qgis_fcgi_socket: 127.0.0.1:7200
qgis_num_workers: 4
qgis_server_log_level: 1
qgis_server_plugin_directory: /srv/qgis/plugins
qgis_install_source: repository
qgis_server_plugins:
  wfsOutputExtension:
    repository: https://github.com/3liz/qgis-wfsOutputExtension
    version: master
qgis_repository_debian: http://qgis.org/debian-ltr
qgis_repository_debian_key: '51F523511C7028C3'
qgis_repository_debian_key_url: 'http://qgis.org/downloads/qgis-2019.gpg.key'

postgresql_install: false
# postgresql_apt_key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
# postgresql_version: 11
# postgresql_encoding: UTF-8
# postgresql_locale: fr_FR.UTF-8
# postgresql_database: lizmap
# postgresql_lizmap_user: lizmap
# postgresql_postgis_version: 2.5
# postgresql_postgres_password: "lizmap1234!"
# postgresql_lizmap_password: "lizmap1234!"



# xvfb_install: true
# xvfb_port: 99
```


2. fired up the creation of the virtual machine in cmd: `D:\IDROSTUDI\LAVORI\GIS\lizmap-web-client\vagrant>vagrant up`
the last lines of the output are (the complete output is 334 lines):

```
PLAY RECAP *********************************************************************
default                    : ok=67   changed=57   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

the FATAL! errors are just:

```
TASK [ldap : remove all current ldap entries] **********************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "ldapdelete -x -c -D cn=admin,dc=lizmap,dc=local -w passlizmap -f /opt/ldap_delete.ldif", "delta": "0:00:00.008254", "end": "2019-11-13 15:42:04.964382", "failed": true, "rc": 32, "start": "2019-11-13 15:42:04.956128", "stderr": "ldap_delete: No such object (32)\n\tmatched DN: dc=lizmap,dc=local\nldap_delete: No such object (32)\n\tmatched DN: dc=lizmap,dc=local\nldap_delete: No such object (32)\n\tmatched DN: dc=lizmap,dc=local\nldap_delete: No such object (32)\n\tmatched DN: dc=lizmap,dc=local\nldap_delete: No such object (32)\n\tmatched DN: dc=lizmap,dc=local\nldap_delete: No such object (32)\n\tmatched DN: dc=lizmap,dc=local\nldap_delete: No such object (32)\n\tmatched DN: dc=lizmap,dc=local", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
```

```
TASK [lizmap : Set rights on dirs] *********************************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "cd /lizmap_web_client && lizmap/install/set_rights.sh vagrant vagrant", "delta": "0:00:00.008664", "end": "2019-11-13 15:42:57.968266", "failed": true, "rc": 127, "start": "2019-11-13 15:42:57.959602", "stderr": "/bin/sh: 1: lizmap/install/set_rights.sh: not found", "stdout": "", "stdout_lines": [], "warnings": []}
```


3. on http://127.0.0.1:8130/ it says _Welcome to nginx!_ and in http://127.0.0.1:8131/ it says _ERR_CONNECTION_RESET_
