### ISSUE TITLE
header - rectangular logo instead of round

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1249]
hi

i need a rectangualr logo in header, like this:
![cascade19](https://user-images.githubusercontent.com/10053874/58157038-663d0580-7c6f-11e9-86ec-83b93960fcf0.png)
how can i do it with "additional CSS properties" or  through other way?...

please help me
thanks in advanced

**Comment by bgisb** [comment]
Hi!

As far as I know, there is a possibility to change a logo in the configuration panel, but we had an issue with word "Login" or "Administration" on it. 
![confggg](https://user-images.githubusercontent.com/48524622/58246518-8fd15c00-7d57-11e9-9494-34e1f15ff034.png)

Finally, we have just switched some graphics on the server:
your_host/www/lizmap-web-client-3.2.1/lizmap/var/lizmap-theme-config/logo.png

**Comment by josemvm** [comment]
hi @bgisb 

thanks for your answer (i know that)!

this is my issue:

![imagem](https://user-images.githubusercontent.com/10053874/58263754-84d8f480-7d74-11e9-82e4-8b27eea5a447.png)

 ![imagem](https://user-images.githubusercontent.com/10053874/58264101-2f511780-7d75-11e9-8ba8-3817dcee3ece.png) <== ![imagem](https://user-images.githubusercontent.com/10053874/58264424-c5853d80-7d75-11e9-941a-69346b361dc9.png) 

![imagem](https://user-images.githubusercontent.com/10053874/58264253-7212ef80-7d75-11e9-96ff-c5fe61ddd128.png)

the lwc keep the logo width

thanks

**Comment by josemvm** [comment]
we need to change the logo `min-width: 60px;`
i'm asking for css code to insert in the "Theme configuration, Additional CSS properties"

**Comment by josemvm** [comment]
something like this :-)

```
#logo {
min-width: 167px;
}
```

**Comment by josemvm** [comment]
but we have problems in mobile mode:
![imagem](https://user-images.githubusercontent.com/10053874/58267537-ba351080-7d7b-11e9-8269-eac199950ed9.png)

**Comment by gioman** [comment]
> but we have problems in mobile mode:

you can use conditions in CSS, i.e.: https://stackoverflow.com/questions/16156225/how-to-change-css-based-on-mobile-device

**Comment by rldhont** [comment]
@josemvm something like that https://cartophyl.lizmap.com/demo/

**Comment by josemvm** [comment]
thanks @rldhont
but what do you mean by pointing to this link? this link has the same issue, the space between logo and header/"Projects - Lizmap"...

**Comment by rldhont** [comment]
```css
@media
only screen and (-webkit-min-device-pixel-ratio: 2),
only screen and (   min--moz-device-pixel-ratio: 2),
only screen and (     -o-min-device-pixel-ratio: 2/1),
only screen and (        min-device-pixel-ratio: 2),
only screen and (                min-resolution: 192dpi),
only screen and (                min-resolution: 2dppx),
only screen and (                   max-height : 640px) ,
only screen and (                   max-device-height : 640px) { 
  #logo {
    min-width:91px;
  }
}
```
