### ISSUE TITLE
locate dock select /input display:none dinamic style

### ISSUE THREAD

**Issue by brebe** [3liz/lizmap-web-client#1378]
hello dear guys, 
I am trying to figure out locating input fields which are transforming on small displays into select field 
(in fact there are not transforming both fields are always there ) display:none style is added to one or another field depending on screen resolution.

i want to keep input field ALWAYS! which js. do i have to modify to stop display:none style to be added dinamically to the fields? i couldnt find anything. 

Is it jquery.combobox.js?

**Comment by nboisteault** [comment]
Look at media queries in media.css.

**Comment by nboisteault** [comment]
You can force this behavior with some CSS ([doc](https://docs.lizmap.com/current/fr/publish/advanced_lizmap_config.html#creating-simple-themes)) : 
```css
#locate .locate-layer select {display:none!important;}
#locate .locate-layer .custom-combobox {display:inline!important;}
```
