### ISSUE TITLE
Using hyphens in forms

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2238]
### What is the bug?
If the wording of the fields contains too long words, they partially disappear under the input field

### Steps to reproduce the issue

1. Go to QGIS and set a field alias with `complementarity`
2. Go to Lizmap, C
3. Click on Edition, 
4. Add a feature
5. See that `complementarity` disappear under the input field

### Expected behavior

Intelligent hyphenation of words with CSS hyphens rule.
```css
.bloc { 
  -webkit-hyphens: auto;
  -moz-hyphens: auto;
  -ms-hyphens: auto;
  hyphens: auto;
}
```
https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

It can be combined with `word-wrap` or `overflow-wrap` for special cases or languages.

### Environment

 - Lizmap version: 3.4
 - QGIS Server FULL version: 3.10
 - QGIS Desktop FULL version: 3.10
 - OS (Windows, Linux, MacOS, Android…): All
 - Browser (Firefox, Chrome…): All
