### ISSUE TITLE
Let's use CSS variables instead of generating CSS file

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-web-client#3096]
### Is your feature request related to a problem? Please describe

In some place in our code, we generate some CSS content in order to set dynamically some CSS properties. Example:

```php
$cssContent .= "#content.atlas-visible:not(.mobile) #right-dock {width: ${atlasWidth}%; max-width: ${atlasWidth}%;}";
$cssContent .= "#content.atlas-visible:not(.mobile) #map-content {margin-right: ${atlasWidth}%;}";
$css = '<style type="text/css">'.$cssContent.'</style>';
```
The problem is that we have to generate inline CSS content that is not recommended in term of security. And this is a content that it cannot saved into cache.

### Describe the solution you'd like

A solution may be a controller, that generate a global CSS stylesheet (probably corresponding to a specific map) declaring only CSS variables. And we link to this CSS stylesheet, as well as other CSS stylesheets that are now statics.

In our example, we could have in one of our static CSS files, these rules:

```css
#content.atlas-visible:not(.mobile) #right-dock {
   width: var(--atlas-width); 
   max-width:var(--atlas-width);
}
#content.atlas-visible:not(.mobile) #map-content {
   margin-right: var(--atlas-width);
}
```

And to generate our dynamic style sheet for each map:

```php
function mapStyleSheet() {
   $rep = $this->getResponse('css');
   $rep->content = ':root {';

   // ....
   if ($lproj->hasAtlasEnabled()) {
     $atlasWidth = $lproj->getOption('atlasMaxWidth');
   }
   else {
      $atlasWidth = "0px"; // or an other default value
   }
    $rep->content .= "--atlas-width: ".$atlasWidth.";\n";
   // ...
   $rep->content .="}";
   return $rep;
}
```

And in lizMap.classic.php:

```php
$rep->addCssLink(jUrl::get('view~lizMap:mapStyleSheet')); // probably before any other CSS stylesheets
```

CSS variables are supported in all browsers since 2018, except into IE of course (but we don't care)
