### ISSUE TITLE
[Bug] loading.gif is not assumed in the theme css project

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-web-client#421]
Hi,
Lizmap is not using theme css loading.gif project for loading map dialog (alternative green squares).

I see the code in here:
\lizmap\www\css\map.css
change de name of the file loading.gif (lizmap\www\css\img folder)  and nothing happens.
and here:
 lizmap\www\themes\default\css\map.css
change the name os loading.gif and the animated gif stay broken and don't use the loading.gif of the theme css project.

So he use the loading.gif of lizmap\www\themes\default\css\map.css instead of css project theme.

Where i can change to do a pull request with the fix. is necessary put some #loading { } parameter in the map.css file?

Regards
João

**Comment by rldhont** [comment]
The `loading.gif` is not displayed with css but with html element.
If you wanna change the `loading.gif`, you have to change the file.

You can propose a fix to do it with css, or update the documentation.

**Comment by rldhont** [comment]
the solution could be:
```js
$('#loading').css('min-height','128px');
```
to fix the loading min-height.
and
```css
#loading p {
  display: none;
}
#loading {
  background-image: url(img/loading.gif);
  background-repeat: no-repeat;
  background-position-x: center;
  background-position-y: center;
}
```
